const BACKEND_BASE_URL = 'http://localhost:3000';
// const BACKEND_BASE_URL = 'https://api.movies-explorer-rkld.nomoredomains.xyz';

const DESKTOP_VIEW_WIDTH = 1250;
const TABLET_VIEW_WIDTH = 765;
const DESKTOP_CARD_COUNT = 12;
const TABLET_CARD_COUNT = 8;
const MOBILE_CARD_COUNT = 5;
const DESKTOP_CARD_COUNT_MORE = 3;
const TABLET_CARD_COUNT_MORE = 2;
const MOBILE_CARD_COUNT_MORE = 2;

export {
  BACKEND_BASE_URL,
  DESKTOP_VIEW_WIDTH,
  TABLET_VIEW_WIDTH,
  DESKTOP_CARD_COUNT,
  TABLET_CARD_COUNT,
  MOBILE_CARD_COUNT,
  DESKTOP_CARD_COUNT_MORE,
  TABLET_CARD_COUNT_MORE,
  MOBILE_CARD_COUNT_MORE
};
